[project]
name = "nickel-launcher"
dynamic = ["version"]
requires-python = "==3.13.5"
dependencies = [
    "httpx>=0.28",
    "ordered-set>=4",
    "pathvalidate>=3",
    "pydantic>=2",
    "pywebview>=5",
    "tendo>=0.3",
    "watchdog>=6",
]

[dependency-groups]
dev = [
    "nuitka>=2",
]

[tool.ruff.isort]
required-imports = ["from __future__ import annotations"]

[tool.ruff.lint.extend-per-file-ignores]
"scripts/build.py" = ["T201"]
